#ifndef _PWM_LED_SHOWS_H_
#define _PWM_LED_SHOWS_H_

#include <stdint.h>

#include "pwm_led.h"

typedef struct {
    uint16_t duration_ms;
    uint8_t red;
    uint8_t green;
    uint8_t blue;
} pwm_led_frame_t;

typedef struct {
    const pwm_led_frame_t *frames;
    uint16_t frame_count;
    uint8_t loop;
} pwm_led_show_t;

#define PWM_LED_FRAME(duration_ms, color_rgb) \
    { \
        (uint16_t)(duration_ms), \
        (uint8_t)(((color_rgb) >> 16) & 0xFF), \
        (uint8_t)(((color_rgb) >> 8) & 0xFF), \
        (uint8_t)((color_rgb) & 0xFF) \
    }

#define PWM_LED_FRAME_COUNT(frames) \
    ((uint16_t)(sizeof(frames) / sizeof((frames)[0])))

#define PWM_LED_SHOW(loop_flag, frames) \
    { \
        (frames), \
        PWM_LED_FRAME_COUNT(frames), \
        (uint8_t)(loop_flag) \
    }

/*
 * Generated by the standalone PWM LED Show Forge editor.
 * Keep this array order aligned with light_show_state_types_t in pwm_led.h.
 */

static const pwm_led_frame_t s_light_show_none[] = {
    PWM_LED_FRAME(0, 0x000000)
};

static const pwm_led_frame_t s_light_show_provisioning[] = {
    PWM_LED_FRAME(32, 0xFFFF00),
    PWM_LED_FRAME(32, 0xF7F700),
    PWM_LED_FRAME(32, 0xEEEE00),
    PWM_LED_FRAME(32, 0xE6E600),
    PWM_LED_FRAME(32, 0xDDDD00),
    PWM_LED_FRAME(32, 0xD5D500),
    PWM_LED_FRAME(32, 0xCCCC00),
    PWM_LED_FRAME(32, 0xC4C400),
    PWM_LED_FRAME(32, 0xBBBB00),
    PWM_LED_FRAME(32, 0xB3B300),
    PWM_LED_FRAME(32, 0xAAAA00),
    PWM_LED_FRAME(32, 0xA2A200),
    PWM_LED_FRAME(32, 0x999900),
    PWM_LED_FRAME(32, 0x919100),
    PWM_LED_FRAME(32, 0x888800),
    PWM_LED_FRAME(32, 0x808000),
    PWM_LED_FRAME(32, 0x777700),
    PWM_LED_FRAME(32, 0x6F6F00),
    PWM_LED_FRAME(32, 0x666600),
    PWM_LED_FRAME(32, 0x5E5E00),
    PWM_LED_FRAME(32, 0x555500),
    PWM_LED_FRAME(32, 0x4D4D00),
    PWM_LED_FRAME(32, 0x444400),
    PWM_LED_FRAME(32, 0x3C3C00),
    PWM_LED_FRAME(32, 0x333300),
    PWM_LED_FRAME(32, 0x2B2B00),
    PWM_LED_FRAME(32, 0x222200),
    PWM_LED_FRAME(32, 0x1A1A00),
    PWM_LED_FRAME(32, 0x111100),
    PWM_LED_FRAME(32, 0x090900),
    PWM_LED_FRAME(564, 0x000000)
};

static const pwm_led_frame_t s_light_show_error[] = {
    PWM_LED_FRAME(200, 0xFF0000),
    PWM_LED_FRAME(32, 0xF70000),
    PWM_LED_FRAME(32, 0xEE0000),
    PWM_LED_FRAME(32, 0xE60000),
    PWM_LED_FRAME(32, 0xDD0000),
    PWM_LED_FRAME(32, 0xD50000),
    PWM_LED_FRAME(32, 0xCC0000),
    PWM_LED_FRAME(32, 0xC40000),
    PWM_LED_FRAME(32, 0xBB0000),
    PWM_LED_FRAME(32, 0xB30000),
    PWM_LED_FRAME(32, 0xAA0000),
    PWM_LED_FRAME(32, 0xA20000),
    PWM_LED_FRAME(32, 0x990000),
    PWM_LED_FRAME(32, 0x910000),
    PWM_LED_FRAME(32, 0x880000),
    PWM_LED_FRAME(32, 0x800000),
    PWM_LED_FRAME(32, 0x770000),
    PWM_LED_FRAME(32, 0x6F0000),
    PWM_LED_FRAME(32, 0x660000),
    PWM_LED_FRAME(32, 0x5E0000),
    PWM_LED_FRAME(32, 0x550000),
    PWM_LED_FRAME(32, 0x4D0000),
    PWM_LED_FRAME(32, 0x440000),
    PWM_LED_FRAME(32, 0x3C0000),
    PWM_LED_FRAME(32, 0x330000),
    PWM_LED_FRAME(32, 0x2B0000),
    PWM_LED_FRAME(32, 0x220000),
    PWM_LED_FRAME(32, 0x1A0000),
    PWM_LED_FRAME(32, 0x110000),
    PWM_LED_FRAME(32, 0x090000),
    PWM_LED_FRAME(64, 0x000000)
};

static const pwm_led_frame_t s_light_show_rgb_test[] = {
    PWM_LED_FRAME(1000, 0xFF0000),
    PWM_LED_FRAME(1000, 0x00FF00),
    PWM_LED_FRAME(1000, 0x0000FF),
    PWM_LED_FRAME(240, 0x000000)
};

static const pwm_led_frame_t s_light_show_startup[] = {
    PWM_LED_FRAME(20, 0x151515),
    PWM_LED_FRAME(20, 0x2C2C2C),
    PWM_LED_FRAME(20, 0x444444),
    PWM_LED_FRAME(20, 0x5B5B5B),
    PWM_LED_FRAME(20, 0x737373),
    PWM_LED_FRAME(20, 0x8A8A8A),
    PWM_LED_FRAME(20, 0xA1A1A1),
    PWM_LED_FRAME(20, 0xB9B9B9),
    PWM_LED_FRAME(20, 0xD0D0D0),
    PWM_LED_FRAME(20, 0xE8E8E8),
    PWM_LED_FRAME(540, 0xFFFFFF),
    PWM_LED_FRAME(20, 0xEAEAEA),
    PWM_LED_FRAME(20, 0xD5D5D5),
    PWM_LED_FRAME(20, 0xBFBFBF),
    PWM_LED_FRAME(20, 0xAAAAAA),
    PWM_LED_FRAME(20, 0x959595),
    PWM_LED_FRAME(20, 0x808080),
    PWM_LED_FRAME(20, 0x6A6A6A),
    PWM_LED_FRAME(20, 0x555555),
    PWM_LED_FRAME(20, 0x404040),
    PWM_LED_FRAME(20, 0x2B2B2B),
    PWM_LED_FRAME(20, 0x151515),
    PWM_LED_FRAME(40, 0x000000)
};

static const pwm_led_frame_t s_light_show_identify[] = {
    PWM_LED_FRAME(20, 0x031500),
    PWM_LED_FRAME(20, 0x062C00),
    PWM_LED_FRAME(20, 0x094400),
    PWM_LED_FRAME(20, 0x0D5B00),
    PWM_LED_FRAME(20, 0x107300),
    PWM_LED_FRAME(20, 0x138A00),
    PWM_LED_FRAME(20, 0x16A100),
    PWM_LED_FRAME(20, 0x19B900),
    PWM_LED_FRAME(20, 0x1DD000),
    PWM_LED_FRAME(20, 0x20E800),
    PWM_LED_FRAME(640, 0x23FF00),
    PWM_LED_FRAME(20, 0x20EA00),
    PWM_LED_FRAME(20, 0x1DD500),
    PWM_LED_FRAME(20, 0x1ABF00),
    PWM_LED_FRAME(20, 0x17AA00),
    PWM_LED_FRAME(20, 0x149500),
    PWM_LED_FRAME(20, 0x128000),
    PWM_LED_FRAME(20, 0x0F6A00),
    PWM_LED_FRAME(20, 0x0C5500),
    PWM_LED_FRAME(20, 0x094000),
    PWM_LED_FRAME(20, 0x062B00),
    PWM_LED_FRAME(20, 0x031500),
    PWM_LED_FRAME(40, 0x000000)
};

static const pwm_led_frame_t s_light_show_wifi_connecting[] = {
    PWM_LED_FRAME(20, 0x040200),
    PWM_LED_FRAME(20, 0x060300),
    PWM_LED_FRAME(20, 0x0D0600),
    PWM_LED_FRAME(20, 0x180B00),
    PWM_LED_FRAME(20, 0x281100),
    PWM_LED_FRAME(20, 0x3D1A00),
    PWM_LED_FRAME(20, 0x552400),
    PWM_LED_FRAME(20, 0x733100),
    PWM_LED_FRAME(20, 0x953F00),
    PWM_LED_FRAME(20, 0xBB4F00),
    PWM_LED_FRAME(540, 0xE66100),
    PWM_LED_FRAME(20, 0xC15200),
    PWM_LED_FRAME(20, 0xA04300),
    PWM_LED_FRAME(20, 0x813700),
    PWM_LED_FRAME(20, 0x662B00),
    PWM_LED_FRAME(20, 0x4E2100),
    PWM_LED_FRAME(20, 0x3A1800),
    PWM_LED_FRAME(20, 0x281100),
    PWM_LED_FRAME(20, 0x1A0B00),
    PWM_LED_FRAME(20, 0x0E0600),
    PWM_LED_FRAME(20, 0x060300),
    PWM_LED_FRAME(20, 0x020100),
    PWM_LED_FRAME(40, 0x000000)
};

static const pwm_led_frame_t s_light_show_sat_conn_pending[] = {
    PWM_LED_FRAME(20, 0x040004),
    PWM_LED_FRAME(20, 0x070007),
    PWM_LED_FRAME(20, 0x0E000E),
    PWM_LED_FRAME(20, 0x1B001B),
    PWM_LED_FRAME(20, 0x2C002C),
    PWM_LED_FRAME(20, 0x430043),
    PWM_LED_FRAME(20, 0x5E005E),
    PWM_LED_FRAME(20, 0x7F007F),
    PWM_LED_FRAME(20, 0xA500A5),
    PWM_LED_FRAME(20, 0xCF00CF),
    PWM_LED_FRAME(540, 0xFF00FF),
    PWM_LED_FRAME(20, 0xD600D6),
    PWM_LED_FRAME(20, 0xB100B1),
    PWM_LED_FRAME(20, 0x8F008F),
    PWM_LED_FRAME(20, 0x710071),
    PWM_LED_FRAME(20, 0x570057),
    PWM_LED_FRAME(20, 0x400040),
    PWM_LED_FRAME(20, 0x2C002C),
    PWM_LED_FRAME(20, 0x1C001C),
    PWM_LED_FRAME(20, 0x100010),
    PWM_LED_FRAME(20, 0x070007),
    PWM_LED_FRAME(20, 0x020002),
    PWM_LED_FRAME(40, 0x000000)
};

static const pwm_led_frame_t s_light_show_ready[] = {
    PWM_LED_FRAME(0, 0x006765)
};

static const pwm_led_frame_t s_light_show_processing[] = {
    PWM_LED_FRAME(0, 0x800080)
};

static const pwm_led_frame_t s_light_show_answer[] = {
    PWM_LED_FRAME(34, 0x0B9100),
    PWM_LED_FRAME(34, 0x0B9300),
    PWM_LED_FRAME(34, 0x0D9A00),
    PWM_LED_FRAME(34, 0x0FA400),
    PWM_LED_FRAME(34, 0x12B100),
    PWM_LED_FRAME(33, 0x15C000),
    PWM_LED_FRAME(33, 0x19D000),
    PWM_LED_FRAME(33, 0x1CDF00),
    PWM_LED_FRAME(33, 0x1FEC00),
    PWM_LED_FRAME(33, 0x21F600),
    PWM_LED_FRAME(33, 0x23FD00),
    PWM_LED_FRAME(466, 0x23FF00),
    PWM_LED_FRAME(34, 0x23FD00),
    PWM_LED_FRAME(34, 0x21F600),
    PWM_LED_FRAME(34, 0x1FEC00),
    PWM_LED_FRAME(33, 0x1CDF00),
    PWM_LED_FRAME(33, 0x19D000),
    PWM_LED_FRAME(33, 0x15C000),
    PWM_LED_FRAME(33, 0x12B100),
    PWM_LED_FRAME(33, 0x0FA400),
    PWM_LED_FRAME(33, 0x0D9A00),
    PWM_LED_FRAME(33, 0x0B9300),
    PWM_LED_FRAME(66, 0x0B9100)
};

static const pwm_led_frame_t s_light_show_listening[] = {
    PWM_LED_FRAME(34, 0x0000FF),
    PWM_LED_FRAME(34, 0x0005FF),
    PWM_LED_FRAME(34, 0x0014FD),
    PWM_LED_FRAME(34, 0x002CFB),
    PWM_LED_FRAME(34, 0x004BF9),
    PWM_LED_FRAME(33, 0x006DF6),
    PWM_LED_FRAME(33, 0x0092F2),
    PWM_LED_FRAME(33, 0x00B4EF),
    PWM_LED_FRAME(33, 0x00D3ED),
    PWM_LED_FRAME(33, 0x00EBEB),
    PWM_LED_FRAME(33, 0x00FAE9),
    PWM_LED_FRAME(466, 0x00FFE9),
    PWM_LED_FRAME(34, 0x00FAE9),
    PWM_LED_FRAME(34, 0x00EBEB),
    PWM_LED_FRAME(34, 0x00D3ED),
    PWM_LED_FRAME(33, 0x00B4EF),
    PWM_LED_FRAME(33, 0x0092F2),
    PWM_LED_FRAME(33, 0x006DF6),
    PWM_LED_FRAME(33, 0x004BF9),
    PWM_LED_FRAME(33, 0x002CFB),
    PWM_LED_FRAME(33, 0x0014FD),
    PWM_LED_FRAME(33, 0x0005FF),
    PWM_LED_FRAME(66, 0x0000FF)
};

static const pwm_led_frame_t s_light_show_volume_up[] = {
    PWM_LED_FRAME(20, 0x151515),
    PWM_LED_FRAME(20, 0x2B2B2B),
    PWM_LED_FRAME(20, 0x404040),
    PWM_LED_FRAME(20, 0x555555),
    PWM_LED_FRAME(20, 0x6A6A6A),
    PWM_LED_FRAME(20, 0x808080),
    PWM_LED_FRAME(20, 0x959595),
    PWM_LED_FRAME(20, 0xAAAAAA),
    PWM_LED_FRAME(20, 0xBFBFBF),
    PWM_LED_FRAME(20, 0xD5D5D5),
    PWM_LED_FRAME(20, 0xEAEAEA),
    PWM_LED_FRAME(20, 0xFFFFFF)
};

static const pwm_led_frame_t s_light_show_volume_down[] = {
    PWM_LED_FRAME(10, 0xFFFFFF),
    PWM_LED_FRAME(20, 0xEAEAEA),
    PWM_LED_FRAME(20, 0xD5D5D5),
    PWM_LED_FRAME(20, 0xBFBFBF),
    PWM_LED_FRAME(20, 0xAAAAAA),
    PWM_LED_FRAME(20, 0x959595),
    PWM_LED_FRAME(20, 0x808080),
    PWM_LED_FRAME(20, 0x6A6A6A),
    PWM_LED_FRAME(20, 0x555555),
    PWM_LED_FRAME(20, 0x404040),
    PWM_LED_FRAME(20, 0x2B2B2B),
    PWM_LED_FRAME(20, 0x151515),
    PWM_LED_FRAME(20, 0x000000)
};

static const pwm_led_show_t g_pwm_led_shows[LIGHT_SHOW_STATE_MAX] = {
    PWM_LED_SHOW(0, s_light_show_none),
    PWM_LED_SHOW(1, s_light_show_provisioning),
    PWM_LED_SHOW(0, s_light_show_error),
    PWM_LED_SHOW(0, s_light_show_rgb_test),
    PWM_LED_SHOW(0, s_light_show_startup),
    PWM_LED_SHOW(0, s_light_show_identify),
    PWM_LED_SHOW(1, s_light_show_wifi_connecting),
    PWM_LED_SHOW(1, s_light_show_sat_conn_pending),
    PWM_LED_SHOW(0, s_light_show_ready),
    PWM_LED_SHOW(0, s_light_show_processing),
    PWM_LED_SHOW(1, s_light_show_answer),
    PWM_LED_SHOW(1, s_light_show_listening),
    PWM_LED_SHOW(0, s_light_show_volume_up),
    PWM_LED_SHOW(0, s_light_show_volume_down)
};

#endif